name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "admin-portal/**"
      - "backend/**"
      - ".github/workflows/**"

jobs:
  # ---------------- LINT: FRONTEND ----------------
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.changed_files), 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Linter
        run: npm run lint --if-present
        working-directory: ./frontend

  # ---------------- LINT: ADMIN PORTAL ----------------
  lint-admin:
    name: Lint Admin Portal
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.changed_files), 'admin-portal/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./admin-portal

      - name: Run Linter
        run: npm run lint --if-present
        working-directory: ./admin-portal

  # ---------------- LINT: BACKEND ----------------
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.changed_files), 'backend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Linter
        run: npm run lint --if-present
        working-directory: ./backend

  # ---------------- FRONTEND BUILD ----------------
  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    if: contains(toJson(github.event.pull_request.changed_files), 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Verify build output
        run: |
          if [ -f "frontend/dist/index.html" ]; then
              echo "✅ Build output valid."
          else
              echo "❌ Build output missing!"
              exit 1
          fi

  # ---------------- ADMIN BUILD ----------------
  admin-build:
    name: Build Admin Portal
    runs-on: ubuntu-latest
    needs: [lint-admin]
    if: contains(toJson(github.event.pull_request.changed_files), 'admin-portal/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./admin-portal

      - name: Build project
        run: npm run build
        working-directory: ./admin-portal

      - name: Verify build output
        run: |
          if [ -f "admin-portal/build/index.html" ]; then
              echo "✅ Build output valid."
          else
              echo "❌ Build output missing!"
              exit 1
          fi

  # ---------------- BACKEND TEST ----------------
  backend-check:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: [lint-backend]
    if: contains(toJson(github.event.pull_request.changed_files), 'backend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Tests
        run: npm test --if-present
        working-directory: ./backend
