name: Format Code

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    prettier:
        if: github.event.action == 'labeled' && github.event.label.name == 'format'
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # Checkout the PR branch with full history
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Prettier
              run: npm install -g prettier

            - name: Format Frontend
              run: |
                  echo "Formatting frontend folder..."
                  prettier --write "frontend/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --config .prettierrc --ignore-path .prettierignore
              continue-on-error: true

            - name: Format Backend
              run: |
                  echo "Formatting backend folder..."
                  prettier --write "backend/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --config .prettierrc --ignore-path .prettierignore
              continue-on-error: true

            - name: commit changes
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                  commit_message: "chore: format code with Prettier"
                  branch: ${{ github.head_ref }}
                  push_options: "--force-with-lease"
                  skip_fetch: false
                  skip_checkout: false
