name: Format Code

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Prettier
              run: npm install -g prettier

            - name: Format Frontend
              run: |
                  echo "Formatting frontend folder..."
                  prettier --write "frontend/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --config .prettierrc --ignore-path .prettierignore
              continue-on-error: true

            - name: Format Backend
              run: |
                  echo "Formatting backend folder..."
                  prettier --write "backend/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --config .prettierrc --ignore-path .prettierignore
              continue-on-error: true

            - name: commit changes
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                  commit_message: "chore: format code with Prettier"
                  # Push to the PR branch
                  branch: ${{ github.head_ref }}
